/**
 * Datamatrix op basis van feitelijke Kwaapo-codebase (Supabase, Workers, Stripe, Expo).
 * Gebruikt voor tests en juridische review — geen verzonnen verwerkingen.
 */

export type DataMatrixRow = {
  category: string;
  source: string;
  purpose: string;
  legalBasis: string;
  retention: string;
  recipients: string;
  internationalTransfer: string;
  required: boolean;
  ifNotProvided: string;
};

export const PRIVACY_DATA_MATRIX: readonly DataMatrixRow[] = [
  {
    category: "Account (e-mail, wachtwoordhash, user-ID)",
    source: "Supabase Auth",
    purpose: "Registratie, login, sessiebeheer",
    legalBasis: "Uitvoering overeenkomst",
    retention: "[BEWAARTERMIJN: account zolang actief]",
    recipients: "Supabase",
    internationalTransfer: "Mogelijk buiten EER — zie hoofdstuk internationale doorgifte",
    required: true,
    ifNotProvided: "Geen account en geen inloggen mogelijk",
  },
  {
    category: "Profiel (username, display_name, bio, avatar, is_private)",
    source: "public.profiles",
    purpose: "Profiel tonen, sociale functies",
    legalBasis: "Uitvoering overeenkomst",
    retention: "[BEWAARTERMIJN: account zolang actief]",
    recipients: "Supabase",
    internationalTransfer: "Mogelijk buiten EER — Supabase",
    required: false,
    ifNotProvided: "Standaardprofiel; sommige functies beperkt",
  },
  {
    category: "Posts, video's, thumbnails, captions, hashtags",
    source: "public.posts + Cloudflare R2 via Worker",
    purpose: "Content publiceren en afspelen",
    legalBasis: "Uitvoering overeenkomst; toestemming voor upload",
    retention: "[BEWAARTERMIJN: posts en media]",
    recipients: "Supabase, Cloudflare (Workers, R2)",
    internationalTransfer: "Cloudflare wereldwijd netwerk",
    required: false,
    ifNotProvided: "Geen eigen content plaatsen",
  },
  {
    category: "Reacties, likes, saves, shares",
    source: "post_comments, post_likes, saved_posts, post_shares",
    purpose: "Sociale interactie en engagement",
    legalBasis: "Uitvoering overeenkomst",
    retention: "[BEWAARTERMIJN: likes, reacties, follows]",
    recipients: "Supabase",
    internationalTransfer: "Mogelijk buiten EER — Supabase",
    required: false,
    ifNotProvided: "Geen interactie met content",
  },
  {
    category: "Follows en volgverzoeken",
    source: "follows, follow_requests",
    purpose: "Sociaal netwerk, feed-personalisatie",
    legalBasis: "Uitvoering overeenkomst",
    retention: "[BEWAARTERMIJN: likes, reacties, follows]",
    recipients: "Supabase",
    internationalTransfer: "Mogelijk buiten EER — Supabase",
    required: false,
    ifNotProvided: "Geen volgers/volgend-lijsten",
  },
  {
    category: "Kijkgedrag (video_views, watch_ms)",
    source: "video_views + Worker feed-telemetrie",
    purpose: "Feed-ranking, creator-affinity",
    legalBasis: "Gerechtvaardigd belang (relevante feed)",
    retention: "[BEWAARTERMIJN: ranking- en kijkgegevens]",
    recipients: "Supabase, Cloudflare Worker",
    internationalTransfer: "Cloudflare Worker",
    required: false,
    ifNotProvided: "Minder gepersonaliseerde feed",
  },
  {
    category: "Content-interacties en tag/creator-voorkeuren",
    source: "content_interactions, user_tag_preferences, user_creator_preferences",
    purpose: "Interest-ranking, aanbevelingen",
    legalBasis: "Gerechtvaardigd belang",
    retention: "[BEWAARTERMIJN: ranking- en kijkgegevens]",
    recipients: "Supabase",
    internationalTransfer: "Mogelijk buiten EER — Supabase",
    required: false,
    ifNotProvided: "Generiekere aanbevelingen",
  },
  {
    category: "Niet-geïnteresseerd / feed-mutes",
    source: "feed_not_interested, user_blocks",
    purpose: "Feed aanpassen, veiligheid",
    legalBasis: "Uitvoering overeenkomst; gerechtvaardigd belang",
    retention: "[BEWAARTERMIJN: ranking- en kijkgegevens]",
    recipients: "Supabase",
    internationalTransfer: "Mogelijk buiten EER — Supabase",
    required: false,
    ifNotProvided: "Minder controle over feed",
  },
  {
    category: "Marketplace-producten",
    source: "public.products",
    purpose: "Aanbod tonen en verkopen",
    legalBasis: "Uitvoering overeenkomst",
    retention: "[BEWAARTERMIJN: posts en media]",
    recipients: "Supabase",
    internationalTransfer: "Mogelijk buiten EER — Supabase",
    required: false,
    ifNotProvided: "Geen verkopen via Kwaapo",
  },
  {
    category: "Bestellingen en verzendgegevens",
    source: "orders, order_items",
    purpose: "Checkout, fulfillment, geschillen",
    legalBasis: "Uitvoering overeenkomst; wettelijke verplichting (administratie)",
    retention: "[BEWAARTERMIJN: betaalde orders]",
    recipients: "Supabase; gedeeld met verkoper/koper",
    internationalTransfer: "Mogelijk buiten EER — Supabase",
    required: true,
    ifNotProvided: "Geen aankoop mogelijk",
  },
  {
    category: "Stripe Checkout / Connect referenties",
    source: "Stripe API + worker-stripe-connect.js",
    purpose: "Betalingen en uitbetalingen",
    legalBasis: "Uitvoering overeenkomst; wettelijke verplichting",
    retention: "[BEWAARTERMIJN: Stripe-referenties]",
    recipients: "Stripe",
    internationalTransfer: "Stripe — mogelijk VS en andere landen",
    required: true,
    ifNotProvided: "Geen betalingen of verkopersuitbetaling",
  },
  {
    category: "KVK-verificatie verkopers",
    source: "worker-seller-readiness.js + KVK API",
    purpose: "Bedrijfsverificatie verkopers",
    legalBasis: "Wettelijke verplichting / gerechtvaardigd belang (fraude)",
    retention: "[BEWAARTERMIJN: fiscale administratie]",
    recipients: "KVK (via Worker), Supabase",
    internationalTransfer: "Nederland (KVK)",
    required: true,
    ifNotProvided: "Geen verkopersaccount",
  },
  {
    category: "Push device tokens",
    source: "push_device_tokens + expo-notifications",
    purpose: "Pushmeldingen",
    legalBasis: "Toestemming (apparaat)",
    retention: "[BEWAARTERMIJN: account zolang actief]",
    recipients: "Expo push service, Apple/Google",
    internationalTransfer: "Mogelijk buiten EER",
    required: false,
    ifNotProvided: "Geen pushmeldingen",
  },
  {
    category: "In-app en seller/buyer notificaties",
    source: "seller_notifications, buyer_notifications, activity_reads",
    purpose: "Activiteit en orderupdates",
    legalBasis: "Uitvoering overeenkomst",
    retention: "[BEWAARTERMIJN: account zolang actief]",
    recipients: "Supabase; Realtime",
    internationalTransfer: "Mogelijk buiten EER — Supabase",
    required: false,
    ifNotProvided: "Minder in-app updates",
  },
  {
    category: "Contact- en supportberichten",
    source: "contact_messages + Edge Function (Resend)",
    purpose: "Klantenservice",
    legalBasis: "Uitvoering overeenkomst; gerechtvaardigd belang",
    retention: "[BEWAARTERMIJN: supportberichten]",
    recipients: "Supabase, Resend",
    internationalTransfer: "Resend — mogelijk buiten EER",
    required: false,
    ifNotProvided: "Geen reactie op support via formulier",
  },
  {
    category: "Meldingen en moderatie",
    source: "post_reports, moderation_reports, user_blocks",
    purpose: "Veiligheid en naleving",
    legalBasis: "Gerechtvaardigd belang; wettelijke verplichting",
    retention: "[BEWAARTERMIJN: meldingen en moderatie]",
    recipients: "Supabase",
    internationalTransfer: "Mogelijk buiten EER — Supabase",
    required: false,
    ifNotProvided: "Minder mogelijkheid om misbruik te melden",
  },
  {
    category: "Spotify-trackmetadata bij upload",
    source: "music_tracks + worker-spotify.js",
    purpose: "Audio bij reels",
    legalBasis: "Uitvoering overeenkomst",
    retention: "[BEWAARTERMIJN: posts en media]",
    recipients: "Spotify API (via Worker), Supabase",
    internationalTransfer: "Spotify — mogelijk buiten EER",
    required: false,
    ifNotProvided: "Geen Spotify-geluid bij upload",
  },
  {
    category: "Technische logs (Worker, IP in requests)",
    source: "Cloudflare Workers logs",
    purpose: "Beveiliging, foutdiagnostiek",
    legalBasis: "Gerechtvaardigd belang",
    retention: "[BEWAARTERMIJN: beveiligingslogs]",
    recipients: "Cloudflare",
    internationalTransfer: "Cloudflare wereldwijd",
    required: true,
    ifNotProvided: "App kan beperkt functioneren",
  },
  {
    category: "Accountverwijdering",
    source: "request_account_deletion RPC",
    purpose: "AVG-recht op verwijdering",
    legalBasis: "Wettelijke verplichting / uitvoering overeenkomst",
    retention: "[BEWAARTERMIJN: verwijderde accounts]",
    recipients: "Supabase",
    internationalTransfer: "Mogelijk buiten EER — Supabase",
    required: false,
    ifNotProvided: "Account blijft actief",
  },
];

/** Leveranciers aangetroffen in package.json, workers of app-config. */
export const VERIFIED_PRIVACY_VENDORS = [
  "Supabase",
  "Cloudflare",
  "Stripe",
  "Expo",
  "Resend",
  "KVK",
  "Spotify",
  "Apple",
] as const;

/** Onderzocht maar niet actief geconfigureerd — niet opnemen als actieve verwerker. */
export const INVESTIGATED_NOT_ACTIVE_VENDORS = [
  "Google Sign-In",
  "Apple Sign In",
  "Firebase Analytics",
  "Sentry",
  "Facebook/Meta SDK",
  "Google Analytics",
  "Amplitude",
  "Mixpanel",
  "Adjust",
  "AppsFlyer",
] as const;
